import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'
import {
  FingerPrintIcon,
  CalendarIcon,
  LightBulbIcon,
} from '@heroicons/react/24/outline'
import GoogleLoginButton from '../components/google-login-button'

const features = [
  {
    name: 'Simple to Use',
    description:
      'Just add a suffix when signing up for newsletters. For example: johndoe+newsletter@gmail.com',
    icon: LightBulbIcon,
  },
  {
    name: 'Original Design',
    description:
      'Read the bundled up messages with the same design they had on the original newsletters.',
    icon: FingerPrintIcon,
  },
  {
    name: 'Once per Week',
    description:
      'Check your inbox only once, so that you can focus on more important tasks during the week.',
    icon: CalendarIcon,
  },
]

const Home: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <script src="https://accounts.google.com/gsi/client" async></script>
        </Head>
        <main className={styles.main}>
          <div className="flex flex-col items-center mb-12 max-w-lg">
            <h1 className={styles.title}>
              <span className={styles.underlineText}>Unclutter</span> your inbox
            </h1>

            <p className={styles.description}>
              Save time by scheduling your newsletters to be received once per
              week.
            </p>

            <GoogleLoginButton text="continue_with" theme="filled_blue" />
          </div>

          <div className="mt-12 max-w-5xl">
            <dl className="space-y-10 md:space-y-0 md:grid md:grid-cols-3 md:gap-x-8 md:gap-y-10">
              {features.map((feature) => (
                <div
                  key={feature.name}
                  className="relative text-center items-center flex flex-col"
                >
                  <div className="flex items-center justify-center h-12 w-12 rounded-md bg-blue-600 text-white">
                    <feature.icon className="h-6 w-6" aria-hidden="true" />
                  </div>
                  <dt className="mt-4 text-xl leading-6 font-semibold text-gray-900">
                    {feature.name}
                  </dt>
                  <dd className="mt-4 text-base font-light text-gray-500">
                    {feature.description}
                  </dd>
                </div>
              ))}
            </dl>
          </div>
        </main>
        <footer className={styles.footer}>
          <p className="text-gray-500">
            © {new Date().getFullYear()} Summail. All rights reserved.
          </p>
        </footer>
      </div>
    </Layout>
  )
}

export default Home
